### PR TITLE
Fix fab, radio-button, radio-group, progress, menu

### PR DESCRIPTION
**Pull request by cwayfinder**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-polymer-elements/26)

### CODE REVIEW

**Comment by cwayfinder** [comment]
Menu sample "before and after" http://screencast.com/t/gNl5UcCjXGl

**Comment by Saulis** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml, line 44 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/26#-Js4440PXQ9UKcjwEuFG)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/02e7de2283cfd8e09af685c64e73dc5b4f5921dc/demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml#L44)):</sup>
Why not use <p:PaperFab> with all elements?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/26)

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml, line 44 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/26#-Js4440PXQ9UKcjwEuFG)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/02e7de2283cfd8e09af685c64e73dc5b4f5921dc/demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml#L44)):</sup>
Yes it should be done with all elements. This approach makes Java API register the element when the first paper-fab is instanciated, so the rest in the page takes advantage of the registration, but actually they are not using the java api at all, and could have problems with properties set previously to the custom element being available. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/26)

**Comment by manolo** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/26)

**Pull request merged**
