### PR TITLE
Workaround to show yellow underline for tabs

### PR DESCRIPTION
**Pull request by amahdy**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-polymer-elements/31)

### CODE REVIEW

**Comment by amahdy** [comment]
Code by @tomivirkki

**Comment by manolo** [comment]
I don't like this approach since it does not fix the component for it's usage in gwt projects, it's just for demo.
There is a new feature in generator, so if you have a PaperTabsBase.java in the folder lib/[papert-tabs-namespace] then PaperTabs.java would extend it instead of PolymerWidget which  should be extended by the PaperTabsBase. 
in PaperTabsBase we could override the onAttach call and do the hack.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/31)

**Comment by amahdy** [comment]
Adding PaperTabsBase.java under lib/com/vaadin/polymer/paper/widget works as expected.

Tried this code and didn't work:

``` java
package com.vaadin.polymer.paper.widget;

import com.google.gwt.core.client.JavaScriptObject;
import com.vaadin.polymer.PolymerWidget;
import com.google.gwt.user.client.Element;

public class PaperTabsBase extends PolymerWidget {

    public PaperTabsBase(String tag, String src, String html) {
        super(tag, src, html);
    }

    @Override
    protected void onAttach() {
        super.onAttach();

        fixTabsSelection(this.getElement());
    }

    // A temporary workaround to fix the underline tab issue
    // Not a solution.
    private native void fixTabsSelection(Element element) /*-{

      element._onResize();
    }-*/;
}
```

Browser gives: `element_0_g$._onResize is not a function`

**Comment by cwayfinder** [comment]
Fixed in https://github.com/vaadin/gwt-polymer-elements/pull/37

**Comment by manolo** [comment]
#37 partially fixes this. So we need both.

**Comment by cwayfinder** [comment]
This PR doesn't help as well. See http://screencast.com/t/7jngL8eK4G

**Pull request merged**
