### PR TITLE
Fix/samples

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-polymer-elements/27)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[demo/pom.xml, line 29 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27#-Js4BS0ePf_LX1FwigXn)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/1cc02c6b4060592a6216f98f75c9f4365779eb78/demo/pom.xml#L29)):</sup>
What are we fetching from here?

---

<sup>**[demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml, line 43 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27#-Js4BuMDPdc0YqNQxTqc)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/1cc02c6b4060592a6216f98f75c9f4365779eb78/demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml#L43)):</sup>
Are you guys doing the same things here with #26 ?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27)

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[demo/pom.xml, line 29 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27#-Js4BS0ePf_LX1FwigXn)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/1cc02c6b4060592a6216f98f75c9f4365779eb78/demo/pom.xml#L29)):</sup>
gwt-2.8.0-SNAPSHOT is under google repos not under default sonatype one

---

<sup>**[demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml, line 43 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27#-Js4BuMDPdc0YqNQxTqc)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/1cc02c6b4060592a6216f98f75c9f4365779eb78/demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml#L43)):</sup>
Seems like Taras and me were working in the same cases, will coordinate with him

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27)

**Comment by cwayfinder** [comment]
Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/RadioGroupSample.ui.xml, line 52 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27#-Js4DkspvzPKFt3M7NYb)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/1cc02c6b4060592a6216f98f75c9f4365779eb78/demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/RadioGroupSample.ui.xml#L52)):</sup>
This is not correct. The checked item is already specified in radio group.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27)

**Comment by manolo** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/RadioGroupSample.ui.xml, line 52 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27#-Js4DkspvzPKFt3M7NYb)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/1cc02c6b4060592a6216f98f75c9f4365779eb78/demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/RadioGroupSample.ui.xml#L52)):</sup>
I see, will remove this

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27)

**Comment by cwayfinder** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml, line 67 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27#-Js4HGSvChAHfxkGHmNe)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/f67a8e26946ec2656a857059be6cc6b4e4431983/demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml#L67)):</sup>
We lose tabindexes. Should we add set/getTabIndex() to PolymerWidget.java?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27)

**Comment by manolo** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml, line 67 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27#-Js4HGSvChAHfxkGHmNe)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/f67a8e26946ec2656a857059be6cc6b4e4431983/demo/src/main/java/com/vaadin/components/gwt/polymer/client/sampler/paper/FabSample.ui.xml#L67)):</sup>
Yes we should

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/27)

**Pull request merged**
