### PR TITLE
Renamed elements to components, updated namespaces.

### PR DESCRIPTION
**Pull request by Saulis**
Connects to vaadin/components-team-tasks#19

[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-polymer-elements/63)

### CODE REVIEW

**Comment by manolo** [comment]
Tested and verified

**Comment by shoemael** [comment]
Could just be me but the View Source .java and .ui.xml links don't seem to be working:

Tested in Chrome 46.0.2490.71/Linux, Firefox 41.0.2/Linux, IE 11/Windows 10

The page doesn't load at all with MS Edge on Windows 10

http://vaadin.github.io/gwt-polymer-elements/demo/#paper/DropdownMenuSample

Bunch of 404's in the javascript console.

**Comment by manolo** [comment]
@shoemael you are right we didn't updated url's, thanks for reporting

**Comment by shoemael** [comment]
Happy to help.  Love the project!

**Pull request merged**
