### PR TITLE
Update Polymer to v1.2.1. Add sample for vaadin-grid

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-polymer-elements/70)

connects to vaadin/components-team-tasks#34
connects to #69

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[package.json, line 8 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/70#-K2LaEm2fxQsf0Ad9ch4)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/6997ff22d522fcef9f654adbe1b6cca95f9dbd2e/package.json#L8)):</sup>
We should have a version number for the `gwt-api-generator` here.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/70)

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[package.json, line 8 [r1]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/70#-K2LaEm2fxQsf0Ad9ch4)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/6997ff22d522fcef9f654adbe1b6cca95f9dbd2e/package.json#L8)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/70)

**Comment by Saulis** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[demo/pom.xml, line 72 [r3]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/70#-K2kh2QwzWMR71nqRWj8)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/564cd9e42b38a3de28fff1d761b32e6f62c54930/demo/pom.xml#L72)):</sup>
Had to fix the version here, `2.7.0` works nicely. `2.8.0-SNAPSHOT` isn't available. `2.6.1` fails.



---

<sup>**[package.json, line 11 [r3]](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/70#-K2khYz9s-dfBqAb6yeC)** ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/564cd9e42b38a3de28fff1d761b32e6f62c54930/package.json#L11)):</sup>
Hard coded to `fa92309` which is the first revision that contains the behaviors in `vaadin-grid-doc.html`



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/70)

**Comment by Saulis** [comment]
Rebased onto origin/master



---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/70)

**Pull request merged**
