### PR TITLE
Prepare 1.7.0

### LINKED ISSUE #133: gwt-polymer framework does not work on ios 10 - any browser
on ios 10 I dont get past the Polymer.importHref(..)
I get the error from the screenshot
screen shot 2016-09-16 at 11 50 24

### PR DESCRIPTION
**Pull request by manolo**
Fixes #133

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/gwt-polymer-elements/134)

### CODE REVIEW

**Comment by tomivirkki** [comment]
_[package.json, line 11 at r3](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134#-KUqAPcLvIDmsKMm0QOb:-KUqAPcMfUAD75VjatpF:b-9va8km) ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/2bd7c84345fc30c051a52615082dcac160fe118f/package.json#L11)):_

> ``` JSON
>   },
>   "scripts": {
>     "postinstall":"node node_modules/gwt-api-generator/bin/gwt-api-generator.js --package=paper-elements,iron-elements,app-elements,platinum-elements,vaadin-core-elements#master,vaadin-context-menu#master,vaadin-split-layout#master,manolo/vaadin-mock-xhr,manolo/vaadin-pouchdb#master --artifactId=vaadin-gwt-polymer-elements --groupId=com.vaadin.polymer --pom && mvn clean install javadoc:jar"
> ```

Talked about this listing with @jouni and came up with the following:
- Perhaps instead of using the version that happens to be master at build-time, we should use fixed releases. This would require the (already drafted and should be good to go) 1.2.0 release of vaadin-core-elements
- manolo/vaadin-mock-xhr and manolo/vaadin-pouchdb are probably included by accident?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134)_

**Comment by manolo** [comment]
Review status: 0 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

_[package.json, line 11 at r3](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134#-KUqAPcLvIDmsKMm0QOb:-KUqDBVN0aJk5CVv0WXW:b86zdbz) ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/2bd7c84345fc30c051a52615082dcac160fe118f/package.json#L11)):_
<details><summary>

<i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>



> Talked about this listing with @jouni and came up with the following:
> - Perhaps instead of using the version that happens to be master at build-time, we should use fixed releases. This would require the (already drafted and should be good to go) 1.2.0 release of vaadin-core-elements
> - manolo/vaadin-mock-xhr and manolo/vaadin-pouchdb are probably included by accident?
>   </details>
>   - yes, we should release 1.2.0 before this? also I need a way to include the two components that seems not be in 1.2.0 (split, context)
>   - yes, I forgot to remove them, I use those in my tests projects, actually the demo project uses the mock but it should not be included in this bundle.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134)_

**Comment by manolo** [comment]
Review status: 0 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

_[package.json, line 11 at r3](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134#-KUqAPcLvIDmsKMm0QOb:-KUwYASNiGJRiOH-mhEB:b-9qdbus) ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/2bd7c84345fc30c051a52615082dcac160fe118f/package.json#L11)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> - yes, we should release 1.2.0 before this? also I need a way to include the two components that seems not be in 1.2.0 (split, context)
> - yes, I forgot to remove them, I use those in my tests projects, actually the demo project uses the mock but it should not be included in this bundle.
> 
> </details>
> 1.- Removed all master references, so as this depends on latest releases.
> 2.- done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134)_

**Comment by tomivirkki** [comment]
_[package.json, line 11 at r3](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134#-KUqAPcLvIDmsKMm0QOb:-KV-WKGpIH7OFfNgULtj:b11lab3) ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/2bd7c84345fc30c051a52615082dcac160fe118f/package.json#L11)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> 1.- Removed all master references, so as this depends on latest releases.
> 2.- done
> </details>
> Now that vaadin-core-elements 1.2 is out, we should depend on that here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134)_

**Comment by manolo** [comment]
Review status: 0 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

_[package.json, line 11 at r3](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134#-KUqAPcLvIDmsKMm0QOb:-KV-X1ica7jN4x-9LkQ6:bjf642c) ([raw file](https://github.com/vaadin/gwt-polymer-elements/blob/2bd7c84345fc30c051a52615082dcac160fe118f/package.json#L11)):_
<details><summary>

<i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>



> Now that vaadin-core-elements 1.2 is out, we should depend on that here.
> </details>
> We don't depend on any specific version for this, it should work with latest stable versions, like iron, paper, etc.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134)_

**Comment by tomivirkki** [comment]
Reviewed 2 of 4 files at r1, 23 of 25 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/gwt-polymer-elements/134)_

**Pull request merged**
